Repository fabian-hiller/valibot, pull requests merged in 2023-10, with the labels that each got.

#117 feat: add intersection schema
  library/CHANGELOG.md
  library/src/methods/brand/brand.ts
  library/src/methods/transform/transform.ts
  library/src/methods/transform/transformAsync.ts
  library/src/schemas/index.ts
  library/src/schemas/intersection/index.ts
  library/src/schemas/intersection/intersection.test.ts
  library/src/schemas/intersection/intersection.ts
  library/src/schemas/intersection/intersectionAsync.test.ts
  library/src/schemas/intersection/intersectionAsync.ts
  library/src/schemas/intersection/types.ts
  library/src/schemas/intersection/utils/index.ts
  library/src/schemas/intersection/utils/mergeOutputs/index.ts
  library/src/schemas/intersection/utils/mergeOutputs/mergeOutputs.test.ts
  library/src/schemas/intersection/utils/mergeOutputs/mergeOutputs.ts
  library/src/schemas/union/union.ts
  library/src/schemas/union/unionAsync.ts
  website/src/routes/api/(async)/intersectionAsync/index.mdx
  website/src/routes/api/(schemas)/intersection/index.mdx
  website/src/routes/api/menu.md
  website/src/routes/guides/(main-concepts)/errors/index.mdx
  website/src/routes/guides/(main-concepts)/schemas/index.mdx
Labels: enhancement, priority

#180 fix: improve email regex
  library/src/validations/email/email.test.ts
  library/src/validations/email/email.ts
Labels: enhancement

#194 Add new validator notValue
  library/CHANGELOG.md
  library/src/validations/bytes/bytes.test.ts
  library/src/validations/bytes/bytes.ts
  library/src/validations/cuid2/cuid2.ts
  library/src/validations/email/email.ts
  library/src/validations/emoji/emoji.ts
  library/src/validations/endsWith/endsWith.ts
  library/src/validations/excludes/excludes.ts
  library/src/validations/imei/imei.ts
  library/src/validations/includes/includes.ts
  library/src/validations/index.ts
  library/src/validations/ip/ip.ts
  library/src/validations/ipv4/ipv4.ts
  library/src/validations/ipv6/ipv6.ts
  library/src/validations/isoDate/isoDate.ts
  library/src/validations/isoDateTime/isoDateTime.ts
  library/src/validations/isoTime/isoTime.ts
  library/src/validations/isoTimeSecond/isoTimeSecond.ts
  library/src/validations/isoTimestamp/isoTimestamp.ts
  library/src/validations/isoWeek/isoWeek.ts
  library/src/validations/length/length.test.ts
  library/src/validations/length/length.ts
  library/src/validations/maxBytes/maxBytes.ts
  library/src/validations/maxLength/maxLength.ts
  library/src/validations/maxSize/maxSize.ts
  library/src/validations/maxValue/maxValue.ts
  library/src/validations/mimeType/mimeType.ts
  library/src/validations/minBytes/minBytes.ts
  library/src/validations/minLength/minLength.ts
  library/src/validations/minSize/minSize.ts
  library/src/validations/minValue/minValue.ts
  library/src/validations/notBytes/index.ts
  library/src/validations/notBytes/notBytes.test.ts
  library/src/validations/notBytes/notBytes.ts
  library/src/validations/notLength/index.ts
  library/src/validations/notLength/notLength.test.ts
  library/src/validations/notLength/notLength.ts
  library/src/validations/notSize/index.ts
  library/src/validations/notSize/notSize.test.ts
  library/src/validations/notSize/notSize.ts
  library/src/validations/notValue/index.ts
  library/src/validations/notValue/notValue.test.ts
  library/src/validations/notValue/notValue.ts
  library/src/validations/regex/regex.ts
  library/src/validations/size/size.test.ts
  library/src/validations/size/size.ts
  library/src/validations/startsWith/startsWith.ts
  library/src/validations/ulid/ulid.ts
  library/src/validations/url/url.ts
  library/src/validations/uuid/uuid.ts
  library/src/validations/value/value.test.ts
  library/src/validations/value/value.ts
  website/src/routes/api/(validations)/notBytes/index.mdx
  website/src/routes/api/(validations)/notLength/index.mdx
  website/src/routes/api/(validations)/notSize/index.mdx
  website/src/routes/api/(validations)/notValue/index.mdx
  website/src/routes/api/menu.md
  website/src/routes/guides/(main-concepts)/pipelines/index.mdx
Labels: enhancement, priority

#208 ci: add lint and format check
  .github/actions/pnpm/action.yml
  .github/workflows/ci.yml
  .github/workflows/node.yml
Labels: enhancement, github

#214 Error on invalid dates
  library/CHANGELOG.md
  library/src/schemas/date/date.test.ts
  library/src/schemas/date/date.ts
  library/src/schemas/date/dateAsync.test.ts
  library/src/schemas/date/dateAsync.ts
  library/src/schemas/number/number.ts
  library/src/schemas/number/numberAsync.ts
Labels: bug, priority

#202 chore: add regexp related eslint plugins
  library/.eslintrc.cjs
  library/CHANGELOG.md
  library/package.json
  library/src/schemas/special/special.test.ts
  library/src/schemas/special/specialAsync.test.ts
  library/src/utils/isLuhnAlgo/isLuhnAlgo.ts
  library/src/validations/cuid2/cuid2.ts
  library/src/validations/email/email.ts
  library/src/validations/emoji/emoji.ts
  library/src/validations/imei/imei.ts
  library/src/validations/ip/ip.ts
  library/src/validations/ipv4/ipv4.ts
  library/src/validations/ipv6/ipv6.ts
  library/src/validations/isoDate/isoDate.ts
  library/src/validations/isoDateTime/isoDateTime.ts
  library/src/validations/isoTime/isoTime.ts
  library/src/validations/isoTimeSecond/isoTimeSecond.ts
  library/src/validations/isoTimestamp/isoTimestamp.ts
  library/src/validations/isoWeek/isoWeek.ts
  library/src/validations/regex/regex.test.ts
  library/src/validations/ulid/ulid.ts
  library/src/validations/uuid/uuid.ts
  pnpm-lock.yaml
Labels: enhancement, priority

#219 Add export for any validation regex
  library/CHANGELOG.md
  library/src/index.ts
  library/src/regex.ts
  library/src/utils/isLuhnAlgo/isLuhnAlgo.ts
  library/src/validations/cuid2/cuid2.ts
  library/src/validations/email/email.ts
  library/src/validations/emoji/emoji.ts
  library/src/validations/imei/imei.ts
  library/src/validations/ip/ip.ts
  library/src/validations/ipv4/ipv4.ts
  library/src/validations/ipv6/ipv6.ts
  library/src/validations/isoDate/isoDate.ts
  library/src/validations/isoDateTime/isoDateTime.ts
  library/src/validations/isoTime/isoTime.ts
  library/src/validations/isoTimeSecond/isoTimeSecond.ts
  library/src/validations/isoTimestamp/isoTimestamp.ts
  library/src/validations/isoWeek/isoWeek.ts
  library/src/validations/ulid/ulid.ts
  library/src/validations/uuid/uuid.ts
Labels: enhancement
