Repository fabian-hiller/valibot, pull requests merged in 2023-08, with the labels that each got.

#43 docs: add typeschema to ecosystem
  website/src/routes/guides/(get-started)/ecosystem/index.mdx
Labels: documentation

#42 Fix ISO validation hours to allow `00`
  library/src/validations/isoDateTime/isoDateTime.test.ts
  library/src/validations/isoDateTime/isoDateTime.ts
  library/src/validations/isoTime/isoTime.test.ts
  library/src/validations/isoTime/isoTime.ts
  library/src/validations/isoTimeSecond/isoTimeSecond.test.ts
  library/src/validations/isoTimeSecond/isoTimeSecond.ts
  library/src/validations/isoTimestamp/isoTimestamp.test.ts
  library/src/validations/isoTimestamp/isoTimestamp.ts
Labels: bug, enhancement

#37 feature: IMEI validation
  library/src/utils/index.ts
  library/src/utils/isLuhnAlgo/index.ts
  library/src/utils/isLuhnAlgo/isLuhnAlgo.test.ts
  library/src/utils/isLuhnAlgo/isLuhnAlgo.ts
  library/src/validations/imei/imei.test.ts
  library/src/validations/imei/imei.ts
  library/src/validations/imei/index.ts
  library/src/validations/index.ts
  website/src/routes/api/(validations)/imei/index.mdx
  website/src/routes/api/menu.md
Labels: enhancement

#59 docs: added missing transform to imports
  website/src/routes/guides/(main-concepts)/infer-types/index.mdx
Labels: documentation

#62 feature: integer validation
  library/src/validations/index.ts
  library/src/validations/integer/index.ts
  library/src/validations/integer/integer.test.ts
  library/src/validations/integer/integer.ts
Labels: enhancement

#67 security: Mitigate Prototype Pollution Vulnerability
  library/src/schemas/record/record.test.ts
  library/src/schemas/record/record.ts
Labels: bug, priority

#64 feat: finite number validation
  library/src/validations/finite/finite.test.ts
  library/src/validations/finite/finite.ts
  library/src/validations/finite/index.ts
  library/src/validations/index.ts
Labels: enhancement

#65 feat: safe integer validation
  library/src/validations/index.ts
  library/src/validations/safe/index.ts
  library/src/validations/safe/safe.test.ts
  library/src/validations/safe/safe.ts
Labels: enhancement

#66 feat: multipleOf validation
  library/src/validations/index.ts
  library/src/validations/multipleOf/index.ts
  library/src/validations/multipleOf/multipleOf.test.ts
  library/src/validations/multipleOf/multipleOf.ts
Labels: enhancement

#71 fix(ci): enable CI on pull requests
  .github/workflows/node.yml
Labels: enhancement, question

#68 refactor(record): prefer arrays over sets for lookups of blocked keys
  library/src/schemas/array/array.ts
  library/src/schemas/object/object.ts
  library/src/schemas/record/record.ts
  library/src/schemas/record/recordAsync.ts
  library/src/schemas/record/values.ts
  library/src/schemas/tuple/tuple.ts
  library/src/utils/executePipe/executePipe.ts
Labels: enhancement, performance

#85 Add brand type
  library/CHANGELOG.md
  library/src/methods/brand/brand.test.ts
  library/src/methods/brand/brand.ts
  library/src/methods/brand/index.ts
  library/src/methods/index.ts
  library/src/methods/transform/transform.ts
  library/src/methods/transform/transformAsync.ts
  website/src/routes/api/(methods)/brand/index.mdx
  website/src/routes/api/menu.md
  website/src/routes/guides/(main-concepts)/methods/index.mdx
Labels: enhancement, good first issue

#46 Reduce spread operators to improve runtime performance
  library/CHANGELOG.md
  library/src/schemas/any/any.ts
  library/src/schemas/any/anyAsync.ts
  library/src/schemas/array/array.ts
  library/src/schemas/array/arrayAsync.ts
  library/src/schemas/bigint/bigint.ts
  library/src/schemas/bigint/bigintAsync.ts
  library/src/schemas/blob/blob.ts
  library/src/schemas/blob/blobAsync.ts
  library/src/schemas/boolean/boolean.ts
  library/src/schemas/boolean/booleanAsync.ts
  library/src/schemas/date/date.ts
  library/src/schemas/date/dateAsync.ts
  library/src/schemas/instance/instance.ts
  library/src/schemas/instance/instanceAsync.ts
  library/src/schemas/map/map.ts
  library/src/schemas/map/mapAsync.ts
  library/src/schemas/number/number.ts
  library/src/schemas/number/numberAsync.ts
  library/src/schemas/object/object.ts
  library/src/schemas/object/objectAsync.ts
  library/src/schemas/record/record.ts
  library/src/schemas/record/recordAsync.ts
  library/src/schemas/set/set.ts
  library/src/schemas/set/setAsync.ts
  library/src/schemas/special/special.ts
  library/src/schemas/special/specialAsync.ts
  library/src/schemas/string/string.ts
  library/src/schemas/string/stringAsync.ts
  library/src/schemas/tuple/tuple.ts
  library/src/schemas/tuple/tupleAsync.ts
  library/src/schemas/unknown/unknown.ts
  library/src/schemas/unknown/unknownAsync.ts
  library/src/utils/getPipeInfo/getPipeInfo.test.ts
  library/src/utils/getPipeInfo/getPipeInfo.ts
  library/src/utils/getPipeInfo/index.ts
  library/src/utils/index.ts
Labels: enhancement, performance

#102 Primitives values in literal schema
  library/CHANGELOG.md
  library/src/schemas/literal/index.ts
  library/src/schemas/literal/literal.test.ts
  library/src/schemas/literal/literal.ts
  library/src/schemas/literal/literalAsync.test.ts
  library/src/schemas/literal/literalAsync.ts
  library/src/schemas/literal/types.ts
Labels: enhancement, priority

#103 Fallback method
  library/CHANGELOG.md
  library/src/methods/fallback/fallback.test.ts
  library/src/methods/fallback/fallback.ts
  library/src/methods/fallback/fallbackAsync.test.ts
  library/src/methods/fallback/fallbackAsync.ts
  library/src/methods/fallback/index.ts
  library/src/methods/fallback/types.ts
  library/src/methods/index.ts
  library/src/methods/withDefault/withDefault.test.ts
  website/src/routes/api/(methods)/fallback/index.mdx
  website/src/routes/guides/(main-concepts)/methods/index.mdx
Labels: enhancement, priority
