Repository fabian-hiller/valibot, pull requests merged in 2023-11, with the labels that each got.

#205 chore: add eslint-plugin-jsdoc
  library/.eslintrc.cjs
  library/CHANGELOG.md
  library/package.json
  library/src/methods/brand/brand.ts
  library/src/schemas/nullish/nullish.ts
  library/src/schemas/union/unionAsync.ts
  library/src/types/pipe.ts
  library/src/types/schema.ts
  library/src/utils/executePipe/executePipeAsync.ts
  library/src/utils/getPipeIssues/getPipeIssues.ts
  pnpm-lock.yaml
Labels: enhancement

#261 fix(not-value): allow not value to accept booleans
  library/CHANGELOG.md
  library/src/validations/notValue/notValue.ts
Labels: enhancement, priority

#273 Add Valimock to Ecosystem page
  website/src/routes/guides/(get-started)/ecosystem/index.mdx
Labels: documentation
