Repository fabian-hiller/valibot, pull requests merged in 2023-12, with the labels that each got.

#220 docs: add string()
  website/src/components/ApiList.tsx
  website/src/components/Property.tsx
  website/src/components/index.ts
  website/src/routes/api/(schemas)/string/index.mdx
  website/src/routes/api/(types)/ArrayPathItem/index.mdx
  website/src/routes/api/(types)/BaseSchema/index.mdx
  website/src/routes/api/(types)/BaseTransformation/index.mdx
  website/src/routes/api/(types)/BaseValidation/index.mdx
  website/src/routes/api/(types)/ErrorMessage/index.mdx
  website/src/routes/api/(types)/InvalidActionResult/index.mdx
  website/src/routes/api/(types)/Issue/index.mdx
  website/src/routes/api/(types)/IssueOrigin/index.mdx
  website/src/routes/api/(types)/IssueReason/index.mdx
  website/src/routes/api/(types)/Issues/index.mdx
  website/src/routes/api/(types)/MapPathItem/index.mdx
  website/src/routes/api/(types)/ObjectPathItem/index.mdx
  website/src/routes/api/(types)/ParseInfo/index.mdx
  website/src/routes/api/(types)/PathItem/index.mdx
  website/src/routes/api/(types)/Pipe/index.mdx
  website/src/routes/api/(types)/PipeActionResult/index.mdx
  website/src/routes/api/(types)/RecordPathItem/index.mdx
  website/src/routes/api/(types)/SchemaResult/index.mdx
  website/src/routes/api/(types)/SetPathItem/index.mdx
  website/src/routes/api/(types)/StringSchema/index.mdx
  website/src/routes/api/(types)/TuplePathItem/index.mdx
  website/src/routes/api/(types)/TypedSchemaResult/index.mdx
  website/src/routes/api/(types)/UnknownPathItem/index.mdx
  website/src/routes/api/(types)/UntypedSchemaResult/index.mdx
  website/src/routes/api/(types)/ValidActionResult/index.mdx
  website/src/routes/api/menu.md
  website/src/routes/guides/(main-concepts)/methods/index.mdx
  website/src/routes/guides/(main-concepts)/pipelines/index.mdx
  website/src/routes/guides/(main-concepts)/schemas/index.mdx
Labels: documentation, priority

#281 feat: TS Config optimisation settings
  library/tsconfig.json
Labels: enhancement

#270 feat: add mac address validation
  library/CHANGELOG.md
  library/src/regex.ts
  library/src/validations/index.ts
  library/src/validations/mac/index.ts
  library/src/validations/mac/mac.test.ts
  library/src/validations/mac/mac.ts
  library/src/validations/mac48/index.ts
  library/src/validations/mac48/mac48.test.ts
  library/src/validations/mac48/mac48.ts
  library/src/validations/mac64/index.ts
  library/src/validations/mac64/mac64.test.ts
  library/src/validations/mac64/mac64.ts
  library/tsconfig.json
  website/src/routes/api/(schemas)/string/index.mdx
  website/src/routes/api/(validations)/mac/index.mdx
  website/src/routes/api/(validations)/mac48/index.mdx
  website/src/routes/api/(validations)/mac64/index.mdx
  website/src/routes/api/menu.md
  website/src/routes/guides/(main-concepts)/pipelines/index.mdx
Labels: enhancement

#284 feat: add bic validation
  library/CHANGELOG.md
  library/src/regex.ts
  library/src/validations/bic/bic.test.ts
  library/src/validations/bic/bic.ts
  library/src/validations/bic/index.ts
  library/src/validations/index.ts
  website/src/routes/api/(schemas)/string/index.mdx
  website/src/routes/api/(validations)/bic/index.mdx
  website/src/routes/api/menu.md
  website/src/routes/guides/(main-concepts)/pipelines/index.mdx
Labels: enhancement

#294 refactor: use typeof func instead func type declaration
  library/src/validations/imei/imei.ts
Labels: enhancement

#295 feat: add downloads, license, npm, ci badges
  README.md
  library/README.md
Labels: documentation

#304 feat: add hexadecimal string validation
  library/CHANGELOG.md
  library/src/regex.ts
  library/src/validations/hex/hex.test.ts
  library/src/validations/hex/hex.ts
  library/src/validations/hex/index.ts
  library/src/validations/index.ts
  website/src/routes/api/(schemas)/any/index.mdx
  website/src/routes/api/(schemas)/string/index.mdx
  website/src/routes/api/(validations)/hex/index.mdx
  website/src/routes/api/menu.md
  website/src/routes/guides/(main-concepts)/pipelines/index.mdx
Labels: enhancement, priority

#308 feat: add hex color validation
  library/CHANGELOG.md
  library/src/regex.ts
  library/src/validations/hexColor/hexColor.test.ts
  library/src/validations/hexColor/hexColor.ts
  library/src/validations/hexColor/index.ts
  library/src/validations/index.ts
  website/src/routes/api/(schemas)/any/index.mdx
  website/src/routes/api/(schemas)/string/index.mdx
  website/src/routes/api/(validations)/hexColor/index.mdx
  website/src/routes/api/menu.md
  website/src/routes/guides/(main-concepts)/pipelines/index.mdx
Labels: enhancement, priority

#292 feat: credit card validation
  library/CHANGELOG.md
  library/src/utils/isLuhnAlgo/isLuhnAlgo.ts
  library/src/validations/creditCard/creditCard.test.ts
  library/src/validations/creditCard/creditCard.ts
  library/src/validations/creditCard/index.ts
  library/src/validations/index.ts
  website/src/routes/api/(schemas)/any/index.mdx
  website/src/routes/api/(schemas)/string/index.mdx
  website/src/routes/api/(validations)/creditCard/index.mdx
  website/src/routes/api/menu.md
  website/src/routes/guides/(main-concepts)/pipelines/index.mdx
Labels: enhancement, priority

#307 feat: hash validation
  library/CHANGELOG.md
  library/src/validations/finite/finite.ts
  library/src/validations/hash/hash.test.ts
  library/src/validations/hash/hash.ts
  library/src/validations/hash/index.ts
  library/src/validations/hexColor/hexColor.ts
  website/src/routes/api/(schemas)/any/index.mdx
  website/src/routes/api/(schemas)/string/index.mdx
  website/src/routes/api/(validations)/hash/index.mdx
  website/src/routes/api/menu.md
  website/src/routes/guides/(main-concepts)/pipelines/index.mdx
Labels: enhancement, priority

#309 feat: add octal validation
  library/CHANGELOG.md
  library/src/regex.ts
  library/src/validations/index.ts
  library/src/validations/octal/index.ts
  library/src/validations/octal/octal.test.ts
  library/src/validations/octal/octal.ts
  website/src/routes/api/(schemas)/any/index.mdx
  website/src/routes/api/(schemas)/string/index.mdx
  website/src/routes/api/(validations)/octal/index.mdx
  website/src/routes/api/menu.md
  website/src/routes/guides/(main-concepts)/pipelines/index.mdx
Labels: enhancement

#300 feat: bump TypeScript version to 5.3.3.
  library/package.json
  package.json
  pnpm-lock.yaml
  website/package.json
Labels: enhancement

#306 feat: add flag --no-isolate to improve performance
  library/vite.config.ts
Labels: enhancement

#316 docs(api): add and fill boolean schema docs
  website/src/routes/api/(schemas)/boolean/index.mdx
  website/src/routes/api/(types)/BooleanSchema/index.mdx
  website/src/routes/api/menu.md
Labels: documentation

#317 docs(api): add and fill symbol schema docs
  website/src/routes/api/(schemas)/symbol/index.mdx
  website/src/routes/api/(types)/SymbolSchema/index.mdx
  website/src/routes/api/menu.md
Labels: documentation

#312 docs: Picklist related docs
  library/CHANGELOG.md
  library/src/schemas/picklist/picklist.ts
  library/src/schemas/picklist/picklistAsync.ts
  library/src/schemas/picklist/types.ts
  website/src/routes/api/(schemas)/picklist/index.mdx
  website/src/routes/api/(types)/MaybeReadonly/index.mdx
  website/src/routes/api/(types)/PicklistOptions/index.mdx
  website/src/routes/api/(types)/PicklistSchema/index.mdx
  website/src/routes/api/menu.md
Labels: documentation

#321 docs(api): Optional related documentation
  website/src/routes/api/(schemas)/optional/index.mdx
  website/src/routes/api/(schemas)/optional/properties.ts
  website/src/routes/api/(types)/OptionalSchema/index.mdx
  website/src/routes/api/(types)/OptionalSchema/properties.ts
  website/src/routes/api/menu.md
Labels: documentation

#328 docs(api): Nullable related docs
  website/src/routes/api/(schemas)/nullable/index.mdx
  website/src/routes/api/(schemas)/nullable/properties.ts
  website/src/routes/api/(types)/NullableSchema/index.mdx
  website/src/routes/api/(types)/NullableSchema/properties.ts
  website/src/routes/api/menu.md
Labels: documentation

#329 docs(api): Nullish related docs
  website/src/routes/api/(schemas)/nullish/index.mdx
  website/src/routes/api/(schemas)/nullish/properties.ts
  website/src/routes/api/(types)/NullishSchema/index.mdx
  website/src/routes/api/(types)/NullishSchema/properties.ts
  website/src/routes/api/menu.md
Labels: documentation

#337 docs(api): Fallback related docs
  library/src/methods/fallback/fallback.ts
  library/src/methods/fallback/fallbackAsync.ts
  website/src/routes/api/(methods)/fallback/index.mdx
  website/src/routes/api/(methods)/fallback/properties.ts
  website/src/routes/api/(types)/FallbackInfo/index.mdx
  website/src/routes/api/(types)/FallbackInfo/properties.ts
  website/src/routes/api/(types)/SchemaWithFallback/index.mdx
  website/src/routes/api/(types)/SchemaWithFallback/properties.ts
  website/src/routes/api/menu.md
Labels: documentation

#331 docs: add number related documentations
  website/src/routes/api/(schemas)/number/index.mdx
  website/src/routes/api/(schemas)/number/properties.ts
  website/src/routes/api/(types)/NumberSchema/index.mdx
  website/src/routes/api/(types)/NumberSchema/properties.ts
  website/src/routes/api/menu.md
Labels: documentation

#330 docs: add array related documentations
  website/src/routes/api/(schemas)/array/index.mdx
  website/src/routes/api/(schemas)/array/properties.ts
  website/src/routes/api/(types)/ArraySchema/index.mdx
  website/src/routes/api/(types)/ArraySchema/properties.ts
  website/src/routes/api/menu.md
Labels: documentation
