Repository fabian-hiller/valibot, pull requests merged in 2023-09, with the labels that each got.

#130 Add support for cuid2s
  library/CHANGELOG.md
  library/src/validations/cuid2/cuid2.test.ts
  library/src/validations/cuid2/cuid2.ts
  library/src/validations/cuid2/index.ts
  library/src/validations/index.ts
  website/src/routes/api/(validations)/cuid2/index.mdx
  website/src/routes/api/menu.md
  website/src/routes/guides/(main-concepts)/pipelines/index.mdx
Labels: enhancement

#138 fix: add InstanceSchema to transformAsync
  library/src/methods/transform/transformAsync.ts
Labels: enhancement, priority

#151 feat: add a validator for the ulid spec
  library/CHANGELOG.md
  library/src/validations/index.ts
  library/src/validations/ulid/index.ts
  library/src/validations/ulid/ulid.test.ts
  library/src/validations/ulid/ulid.ts
  website/src/routes/api/(validations)/ulid/index.mdx
  website/src/routes/api/menu.md
  website/src/routes/guides/(main-concepts)/pipelines/index.mdx
Labels: enhancement

#88 Allow multiple brands and add Unbranded utility
  library/src/methods/brand/brand.test.ts
  library/src/methods/brand/brand.ts
  library/src/methods/brand/index.ts
Labels: enhancement

#164 Add option to skip pipelines when parsing
  library/CHANGELOG.md
  library/src/methods/parse/parse.ts
  library/src/methods/parse/parseAsync.ts
  library/src/methods/safeParse/safeParse.ts
  library/src/methods/safeParse/safeParseAsync.ts
  library/src/schemas/map/map.ts
  library/src/schemas/map/mapAsync.ts
  library/src/schemas/record/record.ts
  library/src/schemas/record/recordAsync.ts
  library/src/types.ts
  library/src/utils/executePipe/executePipe.test.ts
  library/src/utils/executePipe/executePipe.ts
  library/src/utils/executePipe/executePipeAsync.test.ts
  library/src/utils/executePipe/executePipeAsync.ts
  library/src/utils/executePipe/utils/getIssue/getIssue.ts
  library/src/utils/executePipe/utils/getPipeInfo/getPipeInfo.ts
  library/src/utils/getSchemaIssues/getSchemaIssues.ts
  website/src/routes/guides/(main-concepts)/errors/index.mdx
  website/src/routes/guides/(main-concepts)/parse-data/index.mdx
Labels: enhancement, priority

#178 Fix deno import issue for missing file ext and add new linting rule
  library/.eslintrc.cjs
  library/package.json
  library/src/utils/getPipeIssues/getPipeIssues.test.ts
  library/src/validations/ulid/ulid.test.ts
  library/src/validations/ulid/ulid.ts
  pnpm-lock.yaml
Labels: bug, enhancement, priority

#187 docs: StringSchema update
  website/src/routes/guides/(main-concepts)/pipelines/index.mdx
Labels: documentation
