Repository fabian-hiller/valibot, pull requests merged in 2024-06, with the labels that each got.

#611 Codemod for 0.31.0 migration
  codemod/README.md
  codemod/migrate-to-v0.31.0/.codemodrc.json
  codemod/migrate-to-v0.31.0/.gitignore
  codemod/migrate-to-v0.31.0/LICENSE
  codemod/migrate-to-v0.31.0/README.md
  codemod/migrate-to-v0.31.0/__testfixtures__/fixture1.input.ts
  codemod/migrate-to-v0.31.0/__testfixtures__/fixture1.output.ts
  codemod/migrate-to-v0.31.0/__testfixtures__/fixture10.input.ts
  codemod/migrate-to-v0.31.0/__testfixtures__/fixture10.output.ts
  codemod/migrate-to-v0.31.0/__testfixtures__/fixture11.input.ts
  codemod/migrate-to-v0.31.0/__testfixtures__/fixture11.output.ts
  codemod/migrate-to-v0.31.0/__testfixtures__/fixture12.input.ts
  codemod/migrate-to-v0.31.0/__testfixtures__/fixture12.output.ts
  codemod/migrate-to-v0.31.0/__testfixtures__/fixture13.input.ts
  codemod/migrate-to-v0.31.0/__testfixtures__/fixture13.output.ts
  codemod/migrate-to-v0.31.0/__testfixtures__/fixture14.input.ts
  codemod/migrate-to-v0.31.0/__testfixtures__/fixture14.output.ts
  codemod/migrate-to-v0.31.0/__testfixtures__/fixture15.input.ts
  codemod/migrate-to-v0.31.0/__testfixtures__/fixture15.output.ts
  codemod/migrate-to-v0.31.0/__testfixtures__/fixture16.input.ts
  codemod/migrate-to-v0.31.0/__testfixtures__/fixture16.output.ts
  codemod/migrate-to-v0.31.0/__testfixtures__/fixture17.input.ts
  codemod/migrate-to-v0.31.0/__testfixtures__/fixture17.output.ts
  codemod/migrate-to-v0.31.0/__testfixtures__/fixture2.input.ts
  codemod/migrate-to-v0.31.0/__testfixtures__/fixture2.output.ts
  codemod/migrate-to-v0.31.0/__testfixtures__/fixture3.input.ts
  codemod/migrate-to-v0.31.0/__testfixtures__/fixture3.output.ts
  codemod/migrate-to-v0.31.0/__testfixtures__/fixture4.input.ts
  codemod/migrate-to-v0.31.0/__testfixtures__/fixture4.output.ts
  codemod/migrate-to-v0.31.0/__testfixtures__/fixture5.input.ts
  codemod/migrate-to-v0.31.0/__testfixtures__/fixture5.output.ts
  codemod/migrate-to-v0.31.0/__testfixtures__/fixture6.input.ts
  codemod/migrate-to-v0.31.0/__testfixtures__/fixture6.output.ts
  codemod/migrate-to-v0.31.0/__testfixtures__/fixture7.input.ts
  codemod/migrate-to-v0.31.0/__testfixtures__/fixture7.output.ts
  codemod/migrate-to-v0.31.0/__testfixtures__/fixture8.input.ts
  codemod/migrate-to-v0.31.0/__testfixtures__/fixture8.output.ts
  codemod/migrate-to-v0.31.0/__testfixtures__/fixture9.input.ts
  codemod/migrate-to-v0.31.0/__testfixtures__/fixture9.output.ts
  codemod/migrate-to-v0.31.0/package.json
  codemod/migrate-to-v0.31.0/src/index.ts
  codemod/migrate-to-v0.31.0/tsconfig.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: tooling

#625 fix: migrate object and tuples with grit
  .grit/patterns/migrate_to_v0_31_0.md
Labels: enhancement, tooling

#606 feat(i18n): add swedish language
  packages/i18n/.gitignore
  packages/i18n/CHANGELOG.md
  packages/i18n/README.md
  packages/i18n/jsr.json
  packages/i18n/package.json
  packages/i18n/scripts/build-jsr.ts
  packages/i18n/scripts/build-npm.ts
  packages/i18n/src/sv.ts
  packages/i18n/src/types.ts
Labels: enhancement

#605 feat(i18n) Add Italian Language
  packages/i18n/scripts/build-jsr.ts
  packages/i18n/scripts/build-npm.ts
  packages/i18n/src/it.ts
  packages/i18n/src/types.ts
Labels: enhancement

#637 fix(deno): Add missing file extensions
  library/src/types/config.ts
  library/src/utils/entriesFromList/entriesFromList.ts
  library/src/vitest/expectNoActionIssue.ts
  library/src/vitest/expectNoActionIssueAsync.ts
  library/src/vitest/expectNoSchemaIssue.ts
  library/src/vitest/expectNoSchemaIssueAsync.ts
Labels: bug

#649 Modify tupleAsync schema items reference more precise
  library/CHANGELOG.md
  library/src/schemas/looseTuple/looseTuple.ts
  library/src/schemas/looseTuple/looseTupleAsync.ts
  library/src/schemas/strictTuple/strictTuple.ts
  library/src/schemas/strictTuple/strictTupleAsync.ts
  library/src/schemas/tuple/tuple.ts
  library/src/schemas/tuple/tupleAsync.ts
  library/src/schemas/tupleWithRest/tupleWithRest.ts
  library/src/schemas/tupleWithRest/tupleWithRestAsync.ts
Labels: fix

#663 Use type exports where appropriate
  library/src/actions/partialCheck/index.ts
  library/src/actions/rawCheck/index.ts
  library/src/actions/rawTransform/index.ts
Labels: fix

#584 feat: add i18n for the Polish language
  packages/i18n/CHANGELOG.md
  packages/i18n/README.md
  packages/i18n/scripts/build-jsr.ts
  packages/i18n/scripts/build-npm.ts
  packages/i18n/src/pl.ts
  packages/i18n/src/types.ts
Labels: enhancement
