Repository fabian-hiller/valibot, pull requests merged in 2024-12, with the labels that each got.

#940 improve `Flatten errors` section's (issues guide) example
  website/src/routes/guides/(main-concepts)/issues/index.mdx
Labels: documentation

#948 improve `optionals` guide
  website/src/routes/guides/(schemas)/optionals/index.mdx
Labels: documentation

#977 Add valibot-openapi-generator to ecosystem
  website/src/routes/guides/(get-started)/ecosystem/index.mdx
Labels: documentation

#980 Fix typo in minLength documentation
  website/src/routes/api/(actions)/minLength/index.mdx
Labels: documentation

#955 add `nullableAsync` API reference
  website/src/routes/api/(async)/nullableAsync/index.mdx
  website/src/routes/api/(async)/nullableAsync/properties.ts
Labels: documentation

#974 add `transformAsync` & `TransformActionAsync` references
  website/src/routes/api/(async)/transformAsync/index.mdx
  website/src/routes/api/(async)/transformAsync/properties.ts
  website/src/routes/api/(types)/TransformActionAsync/index.mdx
  website/src/routes/api/(types)/TransformActionAsync/properties.ts
  website/src/routes/api/menu.md
Labels: documentation

#989 Fix VariantIssue mdx: issues property not exist
  website/src/routes/api/(types)/VariantIssue/index.mdx
Labels: documentation

#953 add `optionalAsync` API reference
  website/src/routes/api/(async)/optionalAsync/index.mdx
  website/src/routes/api/(async)/optionalAsync/properties.ts
Labels: documentation

#961 add `nullishAsync` API reference
  website/src/routes/api/(async)/nullishAsync/index.mdx
  website/src/routes/api/(async)/nullishAsync/properties.ts
Labels: documentation

#969 add `undefinedableAsync` API reference
  website/src/routes/api/(async)/undefinedableAsync/index.mdx
  website/src/routes/api/(async)/undefinedableAsync/properties.ts
Labels: documentation

#930 feat: Auto-scroll playground's logs container to the latest log message
  website/src/routes/playground/index.tsx
Labels: documentation

#984 Reduce TypeScript target to ES2020
  library/tsconfig.json
  packages/i18n/tsconfig.json
  packages/to-json-schema/tsconfig.json
Labels: fix

#951 feat: add vietnam language
  packages/i18n/.gitignore
  packages/i18n/CHANGELOG.md
  packages/i18n/README.md
  packages/i18n/jsr.json
  packages/i18n/package.json
  packages/i18n/scripts/build-jsr.ts
  packages/i18n/scripts/build-npm.ts
  packages/i18n/src/types.ts
  packages/i18n/src/vi.ts
Labels: enhancement

#973 Only include necessary files for JSR
  library/jsr.json
  packages/i18n/jsr.json
  packages/i18n/scripts/build-jsr.ts
  packages/to-json-schema/jsr.json
Labels: enhancement

#996 fix(i18n/zh-TW): add comma
  packages/i18n/src/zh-TW.ts
Labels: enhancement

#1001 toJsonSchema: Only disallow additionalProperties for strictObject
  packages/to-json-schema/CHANGELOG.md
  packages/to-json-schema/src/convertSchema.test.ts
  packages/to-json-schema/src/convertSchema.ts
  packages/to-json-schema/src/toJsonSchema.test.ts
Labels: priority, fix
