Repository fabian-hiller/valibot, pull requests merged in 2024-03, with the labels that each got.

#468 [i18n] Allow valibot v0.29 in peer dependencies
  packages/i18n/package.json
Labels: enhancement

#470 Added form library Superforms
  website/src/routes/guides/(get-started)/ecosystem/index.mdx
Labels: documentation

#451 Type optimization to solve "type instantiation is excessively deep" error
  library/CHANGELOG.md
  library/src/error/flatten/flatten.ts
  library/src/methods/brand/brand.ts
  library/src/methods/fallback/types.ts
  library/src/methods/transform/types.ts
  library/src/schemas/array/types.ts
  library/src/schemas/enum/enum.ts
  library/src/schemas/map/types.ts
  library/src/schemas/object/object.ts
  library/src/schemas/object/objectAsync.ts
  library/src/schemas/object/types.ts
  library/src/schemas/record/types.ts
  library/src/schemas/set/types.ts
  library/src/schemas/tuple/types.ts
  library/src/schemas/variant/variant.ts
  library/src/schemas/variant/variantAsync.ts
  library/src/types/config.ts
  library/src/types/issues.ts
  library/src/types/pipe.ts
  library/src/types/schema.ts
  library/src/utils/i18n/i18n.ts
  library/src/utils/pipeResult/pipeResult.ts
  library/src/utils/pipeResult/pipeResultAsync.ts
  library/src/utils/pipeResult/utils/pipeIssue/pipeIssue.ts
  library/src/utils/schemaIssue/schemaIssue.ts
  library/src/validations/bic/bic.ts
  library/src/validations/creditCard/creditCard.ts
  library/src/validations/decimal/decimal.ts
  library/src/validations/hash/hash.ts
  library/src/validations/hexColor/hexColor.ts
  library/src/validations/hexadecimal/hexadecimal.ts
  library/src/validations/mac/mac.ts
  library/src/validations/mac48/mac48.ts
  library/src/validations/mac64/mac64.ts
  library/src/validations/octal/octal.ts
Labels: enhancement

#465 Enforce interface consistency with ESLint
  library/.eslintrc.cjs
  library/package.json
  library/src/methods/forward/forward.test.ts
  library/src/methods/forward/forwardAsync.test.ts
Labels: enhancement, tooling
