Repository fabian-hiller/valibot, pull requests merged in 2024-11, with the labels that each got.

#838 Add Farsi language to i18n
  packages/i18n/.gitignore
  packages/i18n/CHANGELOG.md
  packages/i18n/README.md
  packages/i18n/jsr.json
  packages/i18n/package.json
  packages/i18n/scripts/build-jsr.ts
  packages/i18n/scripts/build-npm.ts
  packages/i18n/src/fa.ts
  packages/i18n/src/types.ts
Labels: enhancement

#886 Add czech lang
  packages/i18n/.gitignore
  packages/i18n/CHANGELOG.md
  packages/i18n/README.md
  packages/i18n/jsr.json
  packages/i18n/package.json
  packages/i18n/scripts/build-jsr.ts
  packages/i18n/scripts/build-npm.ts
  packages/i18n/src/cs.ts
  packages/i18n/src/types.ts
Labels: enhancement

#915 little typo
  website/src/routes/guides/(main-concepts)/methods/index.mdx
Labels: documentation

#917 added graphql-codegen-typescript-validation-schema in ecosystem
  website/src/routes/guides/(get-started)/ecosystem/index.mdx
Labels: documentation

#926 Set `typed` = true when the wrapped schema of nonOptional is typed
  library/src/methods/forward/forward.ts
  library/src/methods/forward/forwardAsync.ts
  library/src/schemas/nonNullable/nonNullable.ts
  library/src/schemas/nonNullable/nonNullableAsync.ts
  library/src/schemas/nonNullish/nonNullish.ts
  library/src/schemas/nonNullish/nonNullishAsync.ts
  library/src/schemas/nonOptional/nonOptional.ts
  library/src/schemas/nonOptional/nonOptionalAsync.ts
Labels: fix

#937 improve `value` related API references
  website/src/routes/api/(actions)/value/index.mdx
  website/src/routes/api/(actions)/value/properties.ts
  website/src/routes/api/(types)/ValueAction/index.mdx
Labels: documentation
