Repository fabian-hiller/valibot, pull requests merged in 2024-05, with the labels that each got.

#559 feat(rewrite-with-pipe): add `emoji` action
  .github/actions/pnpm/action.yml
  .github/workflows/ci.yml
  library/src/actions/bic/bic.test.ts
  library/src/actions/creditCard/creditCard.test.ts
  library/src/actions/cuid2/cuid2.test.ts
  library/src/actions/decimal/decimal.test.ts
  library/src/actions/email/email.test.ts
  library/src/actions/emoji/emoji.test-d.ts
  library/src/actions/emoji/emoji.test.ts
  library/src/actions/emoji/emoji.ts
  library/src/actions/emoji/index.ts
  library/src/actions/hexColor/hexColor.test.ts
  library/src/actions/hexadecimal/hexadecimal.test.ts
  library/src/actions/index.ts
  library/src/actions/ip/ip.test.ts
  library/src/actions/ipv4/ipv4.test.ts
  library/src/actions/ipv6/ipv6.test.ts
  library/src/actions/isoTime/isoTime.test.ts
  library/src/actions/isoTimestamp/isoTimestamp.test.ts
  library/src/actions/mac/mac.test.ts
  library/src/actions/mac48/mac48.test.ts
  library/src/actions/mac64/mac64.test.ts
  library/src/actions/octal/octal.test.ts
  library/src/actions/url/url.test.ts
  library/src/regex.ts
  library/src/schemas/string/string.test.ts
Labels: enhancement

#561 feat(rewrite-with-pipe): add `hash` action
  library/src/actions/hash/hash.test-d.ts
  library/src/actions/hash/hash.test.ts
  library/src/actions/hash/hash.ts
  library/src/actions/hash/index.ts
  library/src/actions/index.ts
Labels: enhancement

#564 feat(rewrite-with-pipe): add `isoDate` methods
  library/src/actions/index.ts
  library/src/actions/isoDate/index.ts
  library/src/actions/isoDate/isoDate.test-d.ts
  library/src/actions/isoDate/isoDate.test.ts
  library/src/actions/isoDate/isoDate.ts
  library/src/actions/isoTime/isoTime.test.ts
  library/src/actions/isoTimestamp/isoTimestamp.test.ts
Labels: enhancement

#565 feat(rewrite-with-pipe): add `isoDateTime` validation
  library/src/actions/index.ts
  library/src/actions/isoDateTime/index.ts
  library/src/actions/isoDateTime/isoDateTime.test-d.ts
  library/src/actions/isoDateTime/isoDateTime.test.ts
  library/src/actions/isoDateTime/isoDateTime.ts
Labels: enhancement

#568 feat(rewrite-with-pipe): add `isoWeek` action
  library/src/actions/index.ts
  library/src/actions/isoWeek/index.ts
  library/src/actions/isoWeek/isoWeek.test-d.ts
  library/src/actions/isoWeek/isoWeek.test.ts
  library/src/actions/isoWeek/isoWeek.ts
Labels: enhancement

#570 docs(installation): add jsr
  website/src/routes/guides/(get-started)/installation/index.mdx
Labels: documentation

#560 feat(i18n): add Hungarian translations
  packages/i18n/.gitignore
  packages/i18n/CHANGELOG.md
  packages/i18n/README.md
  packages/i18n/package.json
  packages/i18n/scripts/build.ts
  packages/i18n/src/hu.ts
  packages/i18n/src/types.ts
Labels: enhancement

#577 feat(rewrite-with-pipe): add imei action
  library/src/actions/imei/imei.test-d.ts
  library/src/actions/imei/imei.test.ts
  library/src/actions/imei/imei.ts
  library/src/actions/imei/index.ts
  library/src/actions/index.ts
  library/src/actions/ulid/ulid.test.ts
  library/src/actions/url/url.ts
  library/src/actions/uuid/uuid.test.ts
  library/src/regex.ts
Labels: enhancement

#578 feat(rewrite-with-pipe): add `regex` action
  library/src/actions/index.ts
  library/src/actions/regex/index.ts
  library/src/actions/regex/regex.test-d.ts
  library/src/actions/regex/regex.test.ts
  library/src/actions/regex/regex.ts
Labels: enhancement

#579 feat(rewrite-with-pipe): add `mimeType` action
  library/src/actions/index.ts
  library/src/actions/mimeType/index.ts
  library/src/actions/mimeType/mimeType.test-d.ts
  library/src/actions/mimeType/mimeType.test.ts
  library/src/actions/mimeType/mimeType.ts
Labels: enhancement

#581 feat(i18n) Add Spanish Language
  packages/i18n/CHANGELOG.md
  packages/i18n/README.md
  packages/i18n/scripts/build-jsr.ts
  packages/i18n/scripts/build-npm.ts
  packages/i18n/src/es.ts
  packages/i18n/src/types.ts
Labels: enhancement

#600 Modify variant schema options reference more precise
  library/src/schemas/variant/variant.ts
  library/src/schemas/variant/variantAsync.ts
Labels: enhancement

#591 Add Grit migration script
  .grit/.gitignore
  .grit/grit.yaml
  .grit/patterns/valibot_v03.md
Labels: priority, tooling

#612 fix: exclude unrelated names from codemod
  .grit/patterns/migrate_to_v0_31_0.md
Labels: enhancement
