Repository fabian-hiller/valibot, pull requests merged in 2024-01, with the labels that each got.

#365 doc(api): add `unknown()` related doc
  website/src/routes/api/(schemas)/any/index.mdx
  website/src/routes/api/(schemas)/bigint/index.mdx
  website/src/routes/api/(schemas)/blob/index.mdx
  website/src/routes/api/(schemas)/boolean/index.mdx
  website/src/routes/api/(schemas)/date/index.mdx
  website/src/routes/api/(schemas)/enum_/index.mdx
  website/src/routes/api/(schemas)/instance/index.mdx
  website/src/routes/api/(schemas)/picklist/index.mdx
  website/src/routes/api/(schemas)/string/index.mdx
  website/src/routes/api/(schemas)/symbol/index.mdx
  website/src/routes/api/(schemas)/unknown/index.mdx
  website/src/routes/api/(schemas)/unknown/properties.ts
  website/src/routes/api/(types)/UnknownSchema/index.mdx
  website/src/routes/api/(types)/UnknownSchema/properties.ts
  website/src/routes/api/menu.md
Labels: documentation

#357 docs: add object related documentations
  website/src/routes/api/(schemas)/object/index.mdx
  website/src/routes/api/(schemas)/object/properties.ts
  website/src/routes/api/(types)/ObjectEntries/index.mdx
  website/src/routes/api/(types)/ObjectEntries/properties.ts
  website/src/routes/api/(types)/ObjectInput/index.mdx
  website/src/routes/api/(types)/ObjectOutput/index.mdx
  website/src/routes/api/(types)/ObjectSchema/index.mdx
  website/src/routes/api/(types)/ObjectSchema/properties.ts
  website/src/routes/api/menu.md
Labels: documentation

#353 Add support for 9-digit millisecond precision to isoTimestamp #348
  library/CHANGELOG.md
  library/src/regex.ts
  library/src/validations/isoTimestamp/isoTimestamp.test.ts
  library/src/validations/isoTimestamp/isoTimestamp.ts
Labels: enhancement, priority

#374 docs: removed comma
  website/src/routes/guides/(advanced)/naming-convention/index.mdx
Labels: documentation

#375 fix: starts_with typo
  library/src/validations/startsWith/startsWith.ts
Labels: bug

#339 feat: Add CODE OF CONDUCT, CONTRIBUTING
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: github

#387 fix(deno): fix missing extensions
  library/src/schemas/nonNullable/types.ts
  library/src/schemas/nonNullish/types.ts
  library/src/schemas/nonOptional/types.ts
Labels: bug

#386 docs: BIC validation
  library/src/validations/bic/bic.ts
  website/src/routes/api/(types)/BicValidation/index.mdx
  website/src/routes/api/(types)/BicValidation/properties.ts
  website/src/routes/api/(validations)/bic/index.mdx
  website/src/routes/api/(validations)/bic/properties.ts
  website/src/routes/api/menu.md
Labels: documentation

#388 docs: credit card validation
  library/src/validations/creditCard/creditCard.ts
  website/src/routes/api/(types)/CreditCardValidation/index.mdx
  website/src/routes/api/(types)/CreditCardValidation/properties.ts
  website/src/routes/api/(validations)/creditCard/index.mdx
  website/src/routes/api/(validations)/creditCard/properties.ts
  website/src/routes/api/menu.md
Labels: documentation

#392 docs: hash validation, fix export od hash module
  library/src/validations/hash/hash.ts
  library/src/validations/index.ts
  website/src/routes/api/(types)/HashType/index.mdx
  website/src/routes/api/(types)/HashType/properties.ts
  website/src/routes/api/(types)/HashValidation/index.mdx
  website/src/routes/api/(types)/HashValidation/properties.ts
  website/src/routes/api/(types)/IssueOrigin/index.mdx
  website/src/routes/api/(types)/IssueOrigin/properties.ts
  website/src/routes/api/(types)/IssueReason/index.mdx
  website/src/routes/api/(types)/IssueReason/properties.ts
  website/src/routes/api/(validations)/hash/index.mdx
  website/src/routes/api/(validations)/hash/properties.ts
  website/src/routes/api/menu.md
Labels: documentation

#401 docs: hexColor validation
  library/src/validations/hexColor/hexColor.ts
  website/src/routes/api/(types)/HexColorValidation/index.mdx
  website/src/routes/api/(types)/HexColorValidation/properties.ts
  website/src/routes/api/(validations)/hexColor/index.mdx
  website/src/routes/api/(validations)/hexColor/properties.ts
  website/src/routes/api/menu.md
Labels: documentation
