Repository fabian-hiller/valibot, pull requests merged in 2024-07, with the labels that each got.

#699 docs: add `arrayAsync` schema & `ArraySchemaAsync` type
  website/src/routes/api/(async)/arrayAsync/index.mdx
  website/src/routes/api/(async)/arrayAsync/properties.ts
  website/src/routes/api/(types)/ArraySchemaAsync/index.mdx
  website/src/routes/api/(types)/ArraySchemaAsync/properties.ts
  website/src/routes/api/menu.md
Labels: documentation

#702 fix `isOfType` doc's "Generics" section
  website/src/routes/api/(utils)/isOfType/index.mdx
  website/src/routes/api/(utils)/isOfType/properties.ts
Labels: documentation

#703 docs: add missing pages & `checkAsync` to the async menu
  website/src/routes/api/(async)/parserAsync/index.mdx
  website/src/routes/api/(async)/pipeAsync/index.mdx
  website/src/routes/api/(async)/rawCheckAsync/index.mdx
  website/src/routes/api/(async)/rawTransformAsync/index.mdx
  website/src/routes/api/(async)/safeParserAsync/index.mdx
  website/src/routes/api/menu.md
Labels: documentation

#711 add `MaybePromise` doc
  website/src/routes/api/(types)/MaybePromise/index.mdx
  website/src/routes/api/(types)/MaybePromise/properties.ts
  website/src/routes/api/menu.md
Labels: documentation

#710 add `customAsync` doc
  website/src/routes/api/(async)/customAsync/index.mdx
  website/src/routes/api/(async)/customAsync/properties.ts
Labels: documentation

#712 add 'extends' to `CustomAsyncSchema` def of the API ref
  website/src/routes/api/(types)/CustomSchema/index.mdx
  website/src/routes/api/(types)/CustomSchemaAsync/index.mdx
  website/src/routes/api/(types)/CustomSchemaAsync/properties.ts
Labels: documentation

#715 add `objectAsync` doc & improve `ObjectSchemaAsync` API ref
  website/src/routes/api/(async)/objectAsync/index.mdx
  website/src/routes/api/(async)/objectAsync/properties.ts
  website/src/routes/api/(types)/ObjectSchemaAsync/index.mdx
  website/src/routes/api/(types)/ObjectSchemaAsync/properties.ts
Labels: documentation

#719 improve set input and output types API refs
  website/src/routes/api/(types)/InferSetInput/index.mdx
  website/src/routes/api/(types)/InferSetInput/properties.ts
  website/src/routes/api/(types)/InferSetOutput/index.mdx
  website/src/routes/api/(types)/InferSetOutput/properties.ts
Labels: documentation

#718 add `setAsync` & `SetSchemaAsync` API refs
  website/src/routes/api/(async)/setAsync/index.mdx
  website/src/routes/api/(async)/setAsync/properties.ts
  website/src/routes/api/(types)/SetSchemaAsync/index.mdx
  website/src/routes/api/(types)/SetSchemaAsync/properties.ts
  website/src/routes/api/menu.md
Labels: documentation

#644 feat: add base64 string validation
  library/CHANGELOG.md
  library/src/actions/base64/base64.test-d.ts
  library/src/actions/base64/base64.test.ts
  library/src/actions/base64/base64.ts
  library/src/actions/base64/index.ts
  library/src/actions/index.ts
  library/src/regex.ts
  website/src/routes/api/(actions)/base64/index.mdx
  website/src/routes/api/(async)/customAsync/index.mdx
  website/src/routes/api/(methods)/config/index.mdx
  website/src/routes/api/(methods)/fallback/index.mdx
  website/src/routes/api/(methods)/pipe/index.mdx
  website/src/routes/api/(schemas)/any/index.mdx
  website/src/routes/api/(schemas)/custom/index.mdx
  website/src/routes/api/(schemas)/intersect/index.mdx
  website/src/routes/api/(schemas)/lazy/index.mdx
  website/src/routes/api/(schemas)/string/index.mdx
  website/src/routes/api/(schemas)/union/index.mdx
  website/src/routes/api/(schemas)/unknown/index.mdx
  website/src/routes/api/menu.md
  website/src/routes/guides/(main-concepts)/pipelines/index.mdx
Labels: enhancement

#574 chore(ci): update actions
  .github/actions/pnpm/action.yml
  .github/workflows/ci.yml
Labels: github

#666 Improve regexes
  library/CHANGELOG.md
  library/src/actions/emoji/emoji.test.ts
  library/src/regex.ts
Labels: enhancement, fix

#721 improve `CheckAction` API ref
  website/src/routes/api/(types)/CheckAction/index.mdx
  website/src/routes/api/(types)/CheckAction/properties.ts
Labels: documentation

#720 add `checkAsync` & `CheckActionAsync` API refs
  website/src/routes/api/(async)/checkAsync/index.mdx
  website/src/routes/api/(async)/checkAsync/properties.ts
  website/src/routes/api/(types)/CheckActionAsync/index.mdx
  website/src/routes/api/(types)/CheckActionAsync/properties.ts
  website/src/routes/api/menu.md
Labels: documentation

#727 rename "/MaxSizeIssue " API ref folder to "MaxSizeIssue"
  website/src/routes/api/(types)/MaxSizeIssue/index.mdx
  website/src/routes/api/(types)/MaxSizeIssue/properties.ts
Labels: documentation

#726 add `awaitAsync` API reference
  website/src/routes/api/(async)/awaitAsync/index.mdx
  website/src/routes/api/(async)/awaitAsync/properties.ts
Labels: documentation

#732 fix `fallbackAsync` for async arg & add relevant tests
  library/CHANGELOG.md
  library/src/methods/fallback/fallbackAsync.test.ts
  library/src/methods/fallback/fallbackAsync.ts
Labels: fix

#734 docs: add next-safe-action library to ecosystem page
  website/src/routes/guides/(get-started)/ecosystem/index.mdx
Labels: documentation

#736 add `fallbackAsync` & `SchemaWithFallbackAsync` API refs
  website/src/routes/api/(async)/fallbackAsync/index.mdx
  website/src/routes/api/(async)/fallbackAsync/properties.ts
  website/src/routes/api/(types)/SchemaWithFallbackAsync/index.mdx
  website/src/routes/api/(types)/SchemaWithFallbackAsync/properties.ts
  website/src/routes/api/menu.md
Labels: documentation

#738 Doc: add tupleAsync docs
  website/src/routes/api/(async)/tupleAsync/index.mdx
  website/src/routes/api/(async)/tupleAsync/properties.ts
  website/src/routes/api/(types)/TupleSchemaAsync/index.mdx
  website/src/routes/api/(types)/TupleSchemaAsync/properties.ts
  website/src/routes/api/menu.md
Labels: documentation

#742 add `getDefaultsAsync` API reference
  website/src/routes/api/(async)/getDefaultsAsync/index.mdx
  website/src/routes/api/(async)/getDefaultsAsync/properties.ts
Labels: documentation

#741 Doc: add strictTupleAsync doc
  website/src/routes/api/(async)/strictTupleAsync/index.mdx
  website/src/routes/api/(async)/strictTupleAsync/properties.ts
  website/src/routes/api/(types)/StrictTupleSchemaAsync/index.mdx
  website/src/routes/api/(types)/StrictTupleSchemaAsync/properties.ts
  website/src/routes/api/menu.md
Labels: documentation

#683 chore(i18n): add Indonesian (id) language support
  packages/i18n/.gitignore
  packages/i18n/CHANGELOG.md
  packages/i18n/README.md
  packages/i18n/jsr.json
  packages/i18n/package.json
  packages/i18n/scripts/build-jsr.ts
  packages/i18n/scripts/build-npm.ts
  packages/i18n/src/id.ts
  packages/i18n/src/types.ts
Labels: enhancement

#744 add `getFallbacksAsync` API reference
  website/src/routes/api/(async)/getFallbacksAsync/index.mdx
  website/src/routes/api/(async)/getFallbacksAsync/properties.ts
Labels: documentation

#753 add `looseObjectAsync` API reference
  website/src/routes/api/(async)/looseObjectAsync/index.mdx
  website/src/routes/api/(async)/looseObjectAsync/properties.ts
Labels: documentation

#756 add `strictObjectAsync` API reference
  website/src/routes/api/(async)/strictObjectAsync/index.mdx
  website/src/routes/api/(async)/strictObjectAsync/properties.ts
Labels: documentation
