Repository fabian-hiller/valibot, pull requests merged in 2024-10, with the labels that each got.

#843 improve `minValue` & `maxValue` actions and add missing test cases
  library/CHANGELOG.md
  library/src/actions/maxValue/maxValue.test.ts
  library/src/actions/maxValue/maxValue.ts
  library/src/actions/minValue/minValue.test.ts
  library/src/actions/minValue/minValue.ts
Labels: enhancement

#872 Updated grammar in index.mdx
  website/src/routes/guides/(main-concepts)/parse-data/index.mdx
Labels: documentation

#874 Update index.mdx
  website/src/routes/guides/(get-started)/installation/index.mdx
Labels: fix

#876 docs(website): migrate main concepts away from first-person
  website/src/routes/guides/(advanced)/async-validation/index.mdx
  website/src/routes/guides/(advanced)/internationalization/index.mdx
  website/src/routes/guides/(advanced)/json-schema/index.mdx
  website/src/routes/guides/(advanced)/naming-convention/index.mdx
  website/src/routes/guides/(get-started)/comparison/index.mdx
  website/src/routes/guides/(get-started)/ecosystem/index.mdx
  website/src/routes/guides/(get-started)/installation/index.mdx
  website/src/routes/guides/(get-started)/quick-start/index.mdx
  website/src/routes/guides/(get-started)/use-cases/index.mdx
  website/src/routes/guides/(main-concepts)/infer-types/index.mdx
  website/src/routes/guides/(main-concepts)/issues/index.mdx
  website/src/routes/guides/(main-concepts)/mental-model/index.mdx
  website/src/routes/guides/(main-concepts)/methods/index.mdx
  website/src/routes/guides/(main-concepts)/parse-data/index.mdx
  website/src/routes/guides/(main-concepts)/pipelines/index.mdx
  website/src/routes/guides/(main-concepts)/schemas/index.mdx
  website/src/routes/guides/(migration)/migrate-from-ajv/index.mdx
  website/src/routes/guides/(migration)/migrate-from-joi/index.mdx
  website/src/routes/guides/(migration)/migrate-from-yup/index.mdx
  website/src/routes/guides/(migration)/migrate-to-v0.31.0/index.mdx
  website/src/routes/guides/(schemas)/intersections/index.mdx
  website/src/routes/guides/(schemas)/objects/index.mdx
  website/src/routes/guides/(schemas)/optionals/index.mdx
  website/src/routes/guides/(schemas)/other/index.mdx
  website/src/routes/guides/(schemas)/unions/index.mdx
Labels: documentation, hacktoberfest-accepted

#848 add more valid/invalid cases in `ipv4` action's tests
  library/src/actions/ipv4/ipv4.test.ts
Labels: enhancement

#860 extend `mac48` action tests to cover all scenarios
  library/src/actions/mac48/mac48.test.ts
Labels: enhancement

#869 extend `mac` action tests to cover all scenarios
  library/src/actions/mac/mac.test.ts
Labels: enhancement

#879 add test for every overload signature of 'required' actions
  library/src/methods/required/required.test-d.ts
  library/src/methods/required/required.test.ts
  library/src/methods/required/requiredAsync.test-d.ts
  library/src/methods/required/requiredAsync.test.ts
Labels: enhancement

#873 add unit tests for the `flatten` method
  library/src/methods/flatten/flatten.test.ts
  library/src/methods/flatten/flatten.ts
Labels: enhancement

#877 Add "dependent default" example to `v.optional`
  website/src/routes/guides/(schemas)/optionals/index.mdx
Labels: documentation
