Repository fabian-hiller/valibot, pull requests merged in 2024-09, with the labels that each got.

#808 add `partialCheckAsync` & `PartialCheckActionAsync` API refs
  website/src/routes/api/(async)/partialCheckAsync/index.mdx
  website/src/routes/api/(async)/partialCheckAsync/properties.ts
  website/src/routes/api/(types)/PartialCheckActionAsync/index.mdx
  website/src/routes/api/(types)/PartialCheckActionAsync/properties.ts
  website/src/routes/api/menu.md
Labels: documentation

#809 Improve performance and issues for nested variants
  library/CHANGELOG.md
  library/src/schemas/variant/types.ts
  library/src/schemas/variant/utils/_discriminators/_discriminators.test.ts
  library/src/schemas/variant/utils/_discriminators/_discriminators.ts
  library/src/schemas/variant/utils/_discriminators/index.ts
  library/src/schemas/variant/utils/index.ts
  library/src/schemas/variant/variant.test.ts
  library/src/schemas/variant/variant.ts
  library/src/schemas/variant/variantAsync.test.ts
  library/src/schemas/variant/variantAsync.ts
  website/src/routes/api/(async)/variantAsync/index.mdx
  website/src/routes/api/(schemas)/variant/index.mdx
Labels: enhancement

#812 chore: update docs to include local development
  website/README.md
Labels: documentation

#816 add `partialAsync` & `SchemaWithPartialAsync` API refs
  website/src/routes/api/(async)/partialAsync/index.mdx
  website/src/routes/api/(async)/partialAsync/properties.ts
  website/src/routes/api/(methods)/partial/properties.ts
  website/src/routes/api/(types)/SchemaWithPartial/index.mdx
  website/src/routes/api/(types)/SchemaWithPartialAsync/index.mdx
  website/src/routes/api/menu.md
Labels: documentation

#819 add `requiredAsync` & `SchemaWithRequiredAsync` API refs
  website/src/routes/api/(async)/partialAsync/index.mdx
  website/src/routes/api/(async)/requiredAsync/index.mdx
  website/src/routes/api/(async)/requiredAsync/properties.ts
  website/src/routes/api/(types)/SchemaWithRequiredAsync/index.mdx
  website/src/routes/api/menu.md
Labels: documentation

#821 improve `required` API reference
  website/src/routes/api/(methods)/required/index.mdx
  website/src/routes/api/(methods)/required/properties.ts
  website/src/routes/api/(types)/SchemaWithRequired/index.mdx
  website/src/routes/api/menu.md
Labels: documentation

#825 add `recordAsync` & `RecordSchemaAsync` API refs
  website/src/routes/api/(async)/recordAsync/index.mdx
  website/src/routes/api/(async)/recordAsync/properties.ts
  website/src/routes/api/(async)/requiredAsync/index.mdx
  website/src/routes/api/(types)/RecordSchemaAsync/index.mdx
  website/src/routes/api/(types)/RecordSchemaAsync/properties.ts
  website/src/routes/api/menu.md
Labels: documentation

#802 Initialize @valibot/to-json-schema package
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  packages/to-json-schema/.eslintrc.cjs
  packages/to-json-schema/CHANGELOG.md
  packages/to-json-schema/LICENSE.md
  packages/to-json-schema/README.md
  packages/to-json-schema/jsr.json
  packages/to-json-schema/package.json
  packages/to-json-schema/src/convertAction.test.ts
  packages/to-json-schema/src/convertAction.ts
  packages/to-json-schema/src/convertSchema.test.ts
  packages/to-json-schema/src/convertSchema.ts
  packages/to-json-schema/src/index.ts
  packages/to-json-schema/src/toJsonSchema.test.ts
  packages/to-json-schema/src/toJsonSchema.ts
  packages/to-json-schema/src/type.ts
  packages/to-json-schema/src/utils/index.ts
  packages/to-json-schema/src/utils/throwOrWarn.ts
  packages/to-json-schema/src/vitest/createContext.ts
  packages/to-json-schema/src/vitest/index.ts
  packages/to-json-schema/tsconfig.json
  packages/to-json-schema/tsup.config.ts
  packages/to-json-schema/vite.config.ts
  pnpm-lock.yaml
Labels: enhancement, priority

#834 Update JSON schema tools on ecosystem page
  website/src/routes/guides/(get-started)/ecosystem/index.mdx
Labels: documentation

#854 fix(to-json-schema): Error in JSR
  packages/to-json-schema/src/index.ts
Labels: fix

#855 Docs: add GQLoom to ecosystem
  website/src/routes/guides/(get-started)/ecosystem/index.mdx
Labels: documentation
