Repository fabian-hiller/valibot, pull requests merged in 2025-06, with the labels that each got.

#1215 Add to-json-schema package to playground of website
  .github/actions/environment/action.yml
  website/src/components/CodeEditor.tsx
  website/src/routes/playground/index.tsx
  website/vercel.json
Labels: documentation

#1221 Add Zod-to-Valibot codemod editor to migration guide
  codemod/zod-to-valibot/package.json
  codemod/zod-to-valibot/src/transform/schemas-and-links/schemas-and-links.ts
  codemod/zod-to-valibot/tsconfig.json
  codemod/zod-to-valibot/tsdown.config.ts
  pnpm-lock.yaml
  website/.eslintignore
  website/.prettierignore
  website/package.json
  website/src/components/CodeEditor.tsx
  website/src/routes/guides/(migration)/migrate-from-zod/CodemodEditor.tsx
  website/src/routes/guides/(migration)/migrate-from-zod/index.mdx
  website/src/routes/guides/(migration)/migrate-from-zod/zod/code.ts
  website/src/routes/guides/(migration)/migrate-from-zod/zod/v3/index.d.ts
  website/src/routes/guides/(migration)/migrate-from-zod/zod/v3/package.json
  website/src/routes/guides/(migration)/migrate-from-zod/zod/v4/index.d.ts
  website/src/routes/guides/(migration)/migrate-from-zod/zod/v4/package.json
  website/src/routes/playground/index.tsx
  website/src/utils/trackEvent.ts
  website/tsconfig.json
  website/vercel.json
  website/vite.config.ts
Labels: documentation, size:L

#1236 Fix typo
  website/src/routes/guides/(migration)/migrate-from-zod/index.mdx
Labels: documentation, size:XS
