Repository fabian-hiller/valibot, pull requests merged in 2025-04, with the labels that each got.

#1138 docs: Changed the description of Conform on the EcoSystem page
  website/src/routes/guides/(get-started)/ecosystem/index.mdx
Labels: documentation

#1131 chore: rename vite.config.ts to vitest.config.js
  library/vitest.config.ts
  packages/to-json-schema/vitest.config.ts
Labels: tooling

#1117 Use GitHub profiles in documentation
  library/README.md
  website/src/routes/blog/(posts)/should-we-change-valibots-api/index.mdx
  website/src/routes/guides/(get-started)/introduction/index.mdx
Labels: documentation

#1160 Fix sentence structure in `pick` documentation
  website/src/routes/api/(methods)/pick/index.mdx
Labels: documentation

#1126 Fix arity requirements for tuples converted by `toJsonSchema`
  packages/to-json-schema/CHANGELOG.md
  packages/to-json-schema/src/convertSchema.test.ts
  packages/to-json-schema/src/convertSchema.ts
Labels: enhancement

#1158 Add `summarize` method to summarize issues in multi-line string
  library/CHANGELOG.md
  library/src/methods/index.ts
  library/src/methods/summarize/index.ts
  library/src/methods/summarize/summarize.test.ts
  library/src/methods/summarize/summarize.ts
  website/src/routes/api/(async)/parseAsync/index.mdx
  website/src/routes/api/(async)/parserAsync/index.mdx
  website/src/routes/api/(async)/safeParseAsync/index.mdx
  website/src/routes/api/(async)/safeParserAsync/index.mdx
  website/src/routes/api/(methods)/flatten/index.mdx
  website/src/routes/api/(methods)/parse/index.mdx
  website/src/routes/api/(methods)/parser/index.mdx
  website/src/routes/api/(methods)/safeParse/index.mdx
  website/src/routes/api/(methods)/safeParser/index.mdx
  website/src/routes/api/(methods)/summarize/index.mdx
  website/src/routes/api/(methods)/summarize/properties.ts
  website/src/routes/guides/(main-concepts)/methods/index.mdx
Labels: enhancement

#1167 docs: add isoDate with minValue example
  website/src/routes/api/(actions)/isoDate/index.mdx
Labels: documentation

#1164 Add support for bigints to multipleOf validation action
  library/CHANGELOG.md
  library/src/actions/multipleOf/multipleOf.test-d.ts
  library/src/actions/multipleOf/multipleOf.test.ts
  library/src/actions/multipleOf/multipleOf.ts
  library/src/utils/_stringify/_stringify.ts
  website/src/routes/api/(actions)/multipleOf/index.mdx
  website/src/routes/api/(actions)/multipleOf/properties.ts
  website/src/routes/api/(schemas)/bigint/index.mdx
  website/src/routes/api/(types)/MultipleOfAction/properties.ts
  website/src/routes/api/(types)/MultipleOfIssue/index.mdx
  website/src/routes/api/(types)/MultipleOfIssue/properties.ts
Labels: enhancement

#1171 fix: update nanoid to be more accurate
  library/CHANGELOG.md
  library/src/actions/nanoid/nanoid.test-d.ts
  library/src/actions/nanoid/nanoid.test.ts
  library/src/actions/nanoid/nanoid.ts
  packages/to-json-schema/src/convertAction.ts
  website/src/routes/api/(actions)/nanoid/index.mdx
  website/src/routes/api/(actions)/nanoid/properties.ts
Labels: enhancement
