Repository fabian-hiller/valibot, pull requests merged in 2025-01, with the labels that each got.

#941 Fix issues with enum options filtering logic in enum_ function
  library/CHANGELOG.md
  library/src/schemas/enum/enum.test-d.ts
  library/src/schemas/enum/enum.test.ts
  library/src/schemas/enum/enum.ts
Labels: priority, fix

#962 feat(json): added support for more schema and actions
  packages/to-json-schema/CHANGELOG.md
  packages/to-json-schema/src/convertAction.test.ts
  packages/to-json-schema/src/convertAction.ts
Labels: enhancement, priority

#998 feat: support more actions in JSON schema conversion
  library/eslint.config.js
  library/src/actions/octal/octal.test.ts
  library/src/regex.ts
  packages/to-json-schema/CHANGELOG.md
  packages/to-json-schema/src/convertAction.test.ts
  packages/to-json-schema/src/convertAction.ts
Labels: enhancement

#1003 Update id.ts
  packages/i18n/src/id.ts
Labels: enhancement
