Repository fabian-hiller/valibot, pull requests merged in 2025-07, with the labels that each got.

#1241 Add `@hey-api/openapi-ts` to ecosystem
  website/src/routes/guides/(get-started)/ecosystem/index.mdx
Labels: documentation, size:XS

#1253 Add `svelte-jsonschema-form` to ecosystem page
  website/src/routes/guides/(get-started)/ecosystem/index.mdx
Labels: documentation, size:XS

#1260 Change locale test in _getWordCount unit tests to fix CI error
  library/src/utils/_getWordCount/_getWordCount.test.ts
Labels: fix, size:S

#1259 chore: write output to disk when testing codemod
  codemod/zod-to-valibot/.gitignore
  codemod/zod-to-valibot/src/utils.ts
Labels: tooling, size:XS

#1261 feat: add `or` migration
  codemod/zod-to-valibot/__testfixtures__/or/input.ts
  codemod/zod-to-valibot/__testfixtures__/or/output.ts
  codemod/zod-to-valibot/src/test-setup.test.ts
  codemod/zod-to-valibot/src/transform/schemas-and-links/constants.ts
  codemod/zod-to-valibot/src/transform/schemas-and-links/methods/index.ts
  codemod/zod-to-valibot/src/transform/schemas-and-links/methods/or/index.ts
  codemod/zod-to-valibot/src/transform/schemas-and-links/methods/or/or.ts
  codemod/zod-to-valibot/src/transform/schemas-and-links/schemas-and-links.ts
Labels: enhancement, size:S

#1265 docs: fix 'sting' typo to 'string' across multiple type inference examples
  website/src/routes/api/(types)/InferNonNullableInput/index.mdx
  website/src/routes/api/(types)/InferNonNullableOutput/index.mdx
  website/src/routes/api/(types)/InferNonNullishInput/index.mdx
  website/src/routes/api/(types)/InferNonNullishOutput/index.mdx
  website/src/routes/api/(types)/InferNonOptionalInput/index.mdx
  website/src/routes/api/(types)/InferNonOptionalOutput/index.mdx
Labels: documentation, size:S
