Repository fabian-hiller/valibot, pull requests merged in 2025-02, with the labels that each got.

#1047 Add Valibot v1 RC blog post to website
  website/src/routes/blog/(posts)/valibot-v1-rc-is-available/chapter-nav-dark.jpg
  website/src/routes/blog/(posts)/valibot-v1-rc-is-available/chapter-nav-light.jpg
  website/src/routes/blog/(posts)/valibot-v1-rc-is-available/index.mdx
  website/src/routes/blog/(posts)/valibot-v1-rc-is-available/mental-model-dark.jpg
  website/src/routes/blog/(posts)/valibot-v1-rc-is-available/mental-model-light.jpg
  website/src/routes/blog/(posts)/valibot-v1-rc-is-available/monthly-downloads.webp
  website/src/routes/blog/(posts)/valibot-v1-rc-is-available/object-fix-dark.jpg
  website/src/routes/blog/(posts)/valibot-v1-rc-is-available/object-fix-light.jpg
  website/src/routes/guides/(advanced)/json-schema/index.mdx
Labels: documentation

#985 add `ltValue` action
  library/CHANGELOG.md
  library/src/actions/index.ts
  library/src/actions/ltValue/index.ts
  library/src/actions/ltValue/ltValue.test-d.ts
  library/src/actions/ltValue/ltValue.test.ts
  library/src/actions/ltValue/ltValue.ts
  website/src/routes/api/(actions)/ltValue/index.mdx
  website/src/routes/api/(actions)/ltValue/properties.ts
  website/src/routes/api/(async)/customAsync/index.mdx
  website/src/routes/api/(async)/fallbackAsync/index.mdx
  website/src/routes/api/(async)/intersectAsync/index.mdx
  website/src/routes/api/(async)/lazyAsync/index.mdx
  website/src/routes/api/(async)/pipeAsync/index.mdx
  website/src/routes/api/(async)/unionAsync/index.mdx
  website/src/routes/api/(methods)/config/index.mdx
  website/src/routes/api/(methods)/fallback/index.mdx
  website/src/routes/api/(methods)/pipe/index.mdx
  website/src/routes/api/(schemas)/any/index.mdx
  website/src/routes/api/(schemas)/bigint/index.mdx
  website/src/routes/api/(schemas)/boolean/index.mdx
  website/src/routes/api/(schemas)/custom/index.mdx
  website/src/routes/api/(schemas)/date/index.mdx
  website/src/routes/api/(schemas)/instance/index.mdx
  website/src/routes/api/(schemas)/intersect/index.mdx
  website/src/routes/api/(schemas)/lazy/index.mdx
  website/src/routes/api/(schemas)/number/index.mdx
  website/src/routes/api/(schemas)/string/index.mdx
  website/src/routes/api/(schemas)/union/index.mdx
  website/src/routes/api/(schemas)/unknown/index.mdx
  website/src/routes/api/(types)/LtValueAction/index.mdx
  website/src/routes/api/(types)/LtValueAction/properties.ts
  website/src/routes/api/(types)/LtValueIssue/index.mdx
  website/src/routes/api/(types)/LtValueIssue/properties.ts
  website/src/routes/api/menu.md
  website/src/routes/guides/(main-concepts)/pipelines/index.mdx
  website/src/routes/guides/(migration)/migrate-from-zod/index.mdx
Labels: enhancement, priority

#978 add `gtValue` action
  library/CHANGELOG.md
  library/src/actions/gtValue/gtValue.test.ts
  library/src/actions/gtValue/gtValue.ts
  library/src/actions/gtValue/gtValues.test-d.ts
  library/src/actions/gtValue/index.ts
  library/src/actions/index.ts
  website/src/routes/api/(actions)/gtValue/index.mdx
  website/src/routes/api/(actions)/gtValue/properties.ts
  website/src/routes/api/(async)/customAsync/index.mdx
  website/src/routes/api/(async)/fallbackAsync/index.mdx
  website/src/routes/api/(async)/intersectAsync/index.mdx
  website/src/routes/api/(async)/lazyAsync/index.mdx
  website/src/routes/api/(async)/pipeAsync/index.mdx
  website/src/routes/api/(async)/unionAsync/index.mdx
  website/src/routes/api/(methods)/config/index.mdx
  website/src/routes/api/(methods)/fallback/index.mdx
  website/src/routes/api/(methods)/pipe/index.mdx
  website/src/routes/api/(schemas)/any/index.mdx
  website/src/routes/api/(schemas)/bigint/index.mdx
  website/src/routes/api/(schemas)/boolean/index.mdx
  website/src/routes/api/(schemas)/custom/index.mdx
  website/src/routes/api/(schemas)/date/index.mdx
  website/src/routes/api/(schemas)/instance/index.mdx
  website/src/routes/api/(schemas)/intersect/index.mdx
  website/src/routes/api/(schemas)/lazy/index.mdx
  website/src/routes/api/(schemas)/number/index.mdx
  website/src/routes/api/(schemas)/string/index.mdx
  website/src/routes/api/(schemas)/union/index.mdx
  website/src/routes/api/(schemas)/unknown/index.mdx
  website/src/routes/api/(types)/GtValueAction/index.mdx
  website/src/routes/api/(types)/GtValueAction/properties.ts
  website/src/routes/api/(types)/GtValueIssue/index.mdx
  website/src/routes/api/(types)/GtValueIssue/properties.ts
  website/src/routes/api/menu.md
  website/src/routes/guides/(main-concepts)/pipelines/index.mdx
  website/src/routes/guides/(migration)/migrate-from-zod/index.mdx
Labels: enhancement, priority

#919 add `values` and `notValues` actions
  library/CHANGELOG.md
  library/src/actions/index.ts
  library/src/actions/notValue/notValue.test.ts
  library/src/actions/notValues/index.ts
  library/src/actions/notValues/notValues.test-d.ts
  library/src/actions/notValues/notValues.test.ts
  library/src/actions/notValues/notValues.ts
  library/src/actions/values/index.ts
  library/src/actions/values/values.test-d.ts
  library/src/actions/values/values.test.ts
  library/src/actions/values/values.ts
  website/src/routes/api/(actions)/notValues/index.mdx
  website/src/routes/api/(actions)/notValues/properties.ts
  website/src/routes/api/(actions)/value/index.mdx
  website/src/routes/api/(actions)/values/index.mdx
  website/src/routes/api/(actions)/values/properties.ts
  website/src/routes/api/(async)/customAsync/index.mdx
  website/src/routes/api/(async)/fallbackAsync/index.mdx
  website/src/routes/api/(async)/intersectAsync/index.mdx
  website/src/routes/api/(async)/lazyAsync/index.mdx
  website/src/routes/api/(async)/pipeAsync/index.mdx
  website/src/routes/api/(async)/unionAsync/index.mdx
  website/src/routes/api/(methods)/config/index.mdx
  website/src/routes/api/(methods)/fallback/index.mdx
  website/src/routes/api/(methods)/pipe/index.mdx
  website/src/routes/api/(schemas)/any/index.mdx
  website/src/routes/api/(schemas)/bigint/index.mdx
  website/src/routes/api/(schemas)/boolean/index.mdx
  website/src/routes/api/(schemas)/custom/index.mdx
  website/src/routes/api/(schemas)/date/index.mdx
  website/src/routes/api/(schemas)/instance/index.mdx
  website/src/routes/api/(schemas)/intersect/index.mdx
  website/src/routes/api/(schemas)/lazy/index.mdx
  website/src/routes/api/(schemas)/number/index.mdx
  website/src/routes/api/(schemas)/string/index.mdx
  website/src/routes/api/(schemas)/union/index.mdx
  website/src/routes/api/(schemas)/unknown/index.mdx
  website/src/routes/api/(types)/NotValuesAction/index.mdx
  website/src/routes/api/(types)/NotValuesAction/properties.ts
  website/src/routes/api/(types)/NotValuesIssue/index.mdx
  website/src/routes/api/(types)/NotValuesIssue/properties.ts
  website/src/routes/api/(types)/ValuesAction/index.mdx
  website/src/routes/api/(types)/ValuesAction/properties.ts
  website/src/routes/api/(types)/ValuesIssue/index.mdx
  website/src/routes/api/(types)/ValuesIssue/properties.ts
  website/src/routes/api/menu.md
  website/src/routes/guides/(main-concepts)/pipelines/index.mdx
Labels: enhancement, priority

#910 add `slug` action and its tests
  library/CHANGELOG.md
  library/src/actions/index.ts
  library/src/actions/slug/index.ts
  library/src/actions/slug/slug.test-d.ts
  library/src/actions/slug/slug.test.ts
  library/src/actions/slug/slug.ts
  library/src/regex.ts
  website/src/routes/api/(actions)/slug/index.mdx
  website/src/routes/api/(actions)/slug/properties.ts
  website/src/routes/api/(async)/customAsync/index.mdx
  website/src/routes/api/(async)/fallbackAsync/index.mdx
  website/src/routes/api/(async)/intersectAsync/index.mdx
  website/src/routes/api/(async)/lazyAsync/index.mdx
  website/src/routes/api/(async)/pipeAsync/index.mdx
  website/src/routes/api/(async)/unionAsync/index.mdx
  website/src/routes/api/(methods)/config/index.mdx
  website/src/routes/api/(methods)/fallback/index.mdx
  website/src/routes/api/(methods)/pipe/index.mdx
  website/src/routes/api/(schemas)/any/index.mdx
  website/src/routes/api/(schemas)/custom/index.mdx
  website/src/routes/api/(schemas)/intersect/index.mdx
  website/src/routes/api/(schemas)/lazy/index.mdx
  website/src/routes/api/(schemas)/string/index.mdx
  website/src/routes/api/(schemas)/union/index.mdx
  website/src/routes/api/(schemas)/unknown/index.mdx
  website/src/routes/api/(types)/SlugAction/index.mdx
  website/src/routes/api/(types)/SlugAction/properties.ts
  website/src/routes/api/(types)/SlugIssue/index.mdx
  website/src/routes/api/(types)/SlugIssue/properties.ts
  website/src/routes/api/menu.md
  website/src/routes/guides/(main-concepts)/pipelines/index.mdx
Labels: enhancement, priority

#1023 feat: create `entriesFromObjects` utils
  library/CHANGELOG.md
  library/src/utils/entriesFromObjects/entriesFromObjects.test-d.ts
  library/src/utils/entriesFromObjects/entriesFromObjects.test.ts
  library/src/utils/entriesFromObjects/entriesFromObjects.ts
  library/src/utils/entriesFromObjects/index.ts
  library/src/utils/index.ts
  website/src/routes/api/(utils)/entriesFromObjects/index.mdx
  website/src/routes/api/(utils)/entriesFromObjects/properties.ts
  website/src/routes/api/menu.md
Labels: enhancement, priority

#1054 improve `base64` & its action's API references
  website/src/routes/api/(actions)/base64/index.mdx
  website/src/routes/api/(types)/Base64Action/index.mdx
  website/src/routes/api/(types)/Base64Action/properties.ts
Labels: documentation

#1055 i18n: fix Japanese translation for grapheme
  packages/i18n/src/ja.ts
Labels: fix

#1056 docs: Add warning about combining maxGraphemes with length limiters
  website/src/routes/api/(actions)/maxGraphemes/index.mdx
Labels: documentation
