Repository fabian-hiller/valibot, pull requests merged in 2025-08, with the labels that each got.

#1267 Add piying to ecosystem
  website/src/routes/guides/(get-started)/ecosystem/index.mdx
Labels: documentation, size:XS

#1262 fix: properly migrate `strict` and `passthrough`
  codemod/zod-to-valibot/__testfixtures__/object-extend/input.ts
  codemod/zod-to-valibot/__testfixtures__/object-extend/output.ts
  codemod/zod-to-valibot/__testfixtures__/object-merge/input.ts
  codemod/zod-to-valibot/__testfixtures__/object-merge/output.ts
  codemod/zod-to-valibot/__testfixtures__/object-passthrough/output.ts
  codemod/zod-to-valibot/__testfixtures__/object-strict/output.ts
  codemod/zod-to-valibot/__testfixtures__/object-strip/output.ts
  codemod/zod-to-valibot/src/transform/schemas-and-links/methods/extend/extend.ts
  codemod/zod-to-valibot/src/transform/schemas-and-links/methods/merge/merge.ts
  codemod/zod-to-valibot/src/transform/schemas-and-links/methods/passthrough/passthrough.ts
  codemod/zod-to-valibot/src/transform/schemas-and-links/methods/strict/strict.ts
  codemod/zod-to-valibot/src/transform/schemas-and-links/schemas-and-links.ts
  codemod/zod-to-valibot/src/transform/schemas-and-links/schemas/object/object.ts
  codemod/zod-to-valibot/src/transform/schemas-and-links/types.ts
Labels: fix, size:XXL

#1270 fix: use the ts parser in website codemod playground
  website/src/routes/guides/(migration)/migrate-from-zod/CodemodEditor.tsx
Labels: fix, size:XS

#1271 Update Hey API link to Valibot plugin
  website/src/routes/guides/(get-started)/ecosystem/index.mdx
Labels: documentation, size:XS

#1286 fix(i18n): fix typo for Indonesian lang
  packages/i18n/CHANGELOG.md
  packages/i18n/README.md
Labels: fix, size:XS

#1288 docs: fix source code reference link for DeepPickN
  website/src/routes/api/(types)/DeepPickN/index.mdx
Labels: documentation, size:XS
