Repository fabian-hiller/valibot, pull requests merged in 2025-05, with the labels that each got.

#1137 feat: add JSON parse and stringify actions
  .github/actions/environment/action.yml
  library/CHANGELOG.md
  library/src/actions/index.ts
  library/src/actions/parseJson/index.ts
  library/src/actions/parseJson/parseJson.test-d.ts
  library/src/actions/parseJson/parseJson.test.ts
  library/src/actions/parseJson/parseJson.ts
  library/src/actions/stringifyJson/index.ts
  library/src/actions/stringifyJson/stringifyJson.test-d.ts
  library/src/actions/stringifyJson/stringifyJson.test.ts
  library/src/actions/stringifyJson/stringifyJson.ts
  website/src/components/Property.tsx
  website/src/routes/api/(actions)/parseJson/index.mdx
  website/src/routes/api/(actions)/parseJson/properties.ts
  website/src/routes/api/(actions)/stringifyJson/index.mdx
  website/src/routes/api/(actions)/stringifyJson/properties.ts
  website/src/routes/api/(async)/customAsync/index.mdx
  website/src/routes/api/(async)/fallbackAsync/index.mdx
  website/src/routes/api/(async)/intersectAsync/index.mdx
  website/src/routes/api/(async)/lazyAsync/index.mdx
  website/src/routes/api/(async)/pipeAsync/index.mdx
  website/src/routes/api/(async)/unionAsync/index.mdx
  website/src/routes/api/(methods)/config/index.mdx
  website/src/routes/api/(methods)/fallback/index.mdx
  website/src/routes/api/(methods)/message/index.mdx
  website/src/routes/api/(methods)/pipe/index.mdx
  website/src/routes/api/(schemas)/any/index.mdx
  website/src/routes/api/(schemas)/custom/index.mdx
  website/src/routes/api/(schemas)/intersect/index.mdx
  website/src/routes/api/(schemas)/lazy/index.mdx
  website/src/routes/api/(schemas)/string/index.mdx
  website/src/routes/api/(schemas)/union/index.mdx
  website/src/routes/api/(schemas)/unknown/index.mdx
  website/src/routes/api/(types)/ParseJsonAction/index.mdx
  website/src/routes/api/(types)/ParseJsonAction/properties.ts
  website/src/routes/api/(types)/ParseJsonConfig/index.mdx
  website/src/routes/api/(types)/ParseJsonConfig/properties.ts
  website/src/routes/api/(types)/ParseJsonIssue/index.mdx
  website/src/routes/api/(types)/ParseJsonIssue/properties.ts
  website/src/routes/api/(types)/StringifyJsonAction/index.mdx
  website/src/routes/api/(types)/StringifyJsonAction/properties.ts
  website/src/routes/api/(types)/StringifyJsonConfig/index.mdx
  website/src/routes/api/(types)/StringifyJsonConfig/properties.ts
  website/src/routes/api/(types)/StringifyJsonIssue/index.mdx
  website/src/routes/api/(types)/StringifyJsonIssue/properties.ts
  website/src/routes/api/menu.md
  website/src/routes/guides/(main-concepts)/pipelines/index.mdx
Labels: enhancement

#1176 preserve `string` to `string & {}` transforms on obj vals
  library/CHANGELOG.md
  library/src/schemas/looseObject/looseObject.test-d.ts
  library/src/schemas/looseObject/looseObjectAsync.test-d.ts
  library/src/schemas/object/object.test-d.ts
  library/src/schemas/object/objectAsync.test-d.ts
  library/src/schemas/objectWithRest/objectWithRest.test-d.ts
  library/src/schemas/objectWithRest/objectWithRestAsync.test-d.ts
  library/src/schemas/strictObject/strictObject.test-d.ts
  library/src/schemas/strictObject/strictObjectAsync.test-d.ts
  library/src/types/utils.ts
Labels: priority, fix

#1154 Create getMetadata/getTitle/getDescription methods
  library/CHANGELOG.md
  library/src/methods/getDescription/getDescription.test.ts
  library/src/methods/getDescription/getDescription.ts
  library/src/methods/getDescription/index.ts
  library/src/methods/getMetadata/getMetadata.test-d.ts
  library/src/methods/getMetadata/getMetadata.test.ts
  library/src/methods/getMetadata/getMetadata.ts
  library/src/methods/getMetadata/index.ts
  library/src/methods/getTitle/getTitle.test.ts
  library/src/methods/getTitle/getTitle.ts
  library/src/methods/getTitle/index.ts
  library/src/methods/index.ts
  library/src/methods/pipe/pipe.ts
  library/src/methods/pipe/pipeAsync.ts
  library/src/methods/safeParse/types.ts
  library/src/types/utils.ts
  library/src/utils/_getLastMetadata/_getLastMetadata.test.ts
  library/src/utils/_getLastMetadata/_getLastMetadata.ts
  library/src/utils/_getLastMetadata/index.ts
  library/src/utils/entriesFromObjects/entriesFromObjects.ts
  library/src/utils/index.ts
  website/src/routes/api/(actions)/description/index.mdx
  website/src/routes/api/(actions)/metadata/index.mdx
  website/src/routes/api/(actions)/title/index.mdx
  website/src/routes/api/(methods)/getDescription/index.mdx
  website/src/routes/api/(methods)/getDescription/properties.ts
  website/src/routes/api/(methods)/getMetadata/index.mdx
  website/src/routes/api/(methods)/getMetadata/properties.ts
  website/src/routes/api/(methods)/getTitle/index.mdx
  website/src/routes/api/(methods)/getTitle/properties.ts
  website/src/routes/api/(types)/InferDefaults/index.mdx
  website/src/routes/api/(types)/InferMetadata/index.mdx
  website/src/routes/api/menu.md
  website/src/routes/guides/(main-concepts)/methods/index.mdx
Labels: enhancement

#1181 Add Valibot v1.1 release notes blog post to website
  website/src/components/Credits.tsx
  website/src/logos/MotionLogo.tsx
  website/src/logos/index.ts
  website/src/routes/api/menu.md
  website/src/routes/blog/(posts)/valibot-v1-rc-is-available/index.mdx
  website/src/routes/blog/(posts)/valibot-v1.1-release-notes/index.mdx
Labels: documentation

#1189 feat(to-json-schema): support examples field
  packages/to-json-schema/CHANGELOG.md
  packages/to-json-schema/src/convertAction.test.ts
  packages/to-json-schema/src/convertAction.ts
Labels: enhancement

#1197 Add override config for JSON Schema conversion and add `toJsonSchemaDefs`
  packages/to-json-schema/CHANGELOG.md
  packages/to-json-schema/eslint.config.js
  packages/to-json-schema/src/convertAction.test.ts
  packages/to-json-schema/src/convertAction.ts
  packages/to-json-schema/src/convertSchema.test.ts
  packages/to-json-schema/src/convertSchema.ts
  packages/to-json-schema/src/globalDefs.ts
  packages/to-json-schema/src/index.ts
  packages/to-json-schema/src/toJsonSchema.test.ts
  packages/to-json-schema/src/toJsonSchema.ts
  packages/to-json-schema/src/toJsonSchemaDefs.test.ts
  packages/to-json-schema/src/toJsonSchemaDefs.ts
  packages/to-json-schema/src/type.ts
  packages/to-json-schema/src/utils/addError.ts
  packages/to-json-schema/src/utils/index.ts
Labels: enhancement

#1200 Remove duplicate rawTransformAsync action
  website/src/routes/api/menu.md
Labels: documentation
