Repository fabian-hiller/valibot, pull requests merged in 2025-09, with the labels that each got.

#1273 feat: graceful multiple imports exit + `transform` and `refine`
  codemod/zod-to-valibot/__testfixtures__/multiple-imports-from-zod/input.ts
  codemod/zod-to-valibot/__testfixtures__/multiple-imports-from-zod/output.ts
  codemod/zod-to-valibot/__testfixtures__/refine/input.ts
  codemod/zod-to-valibot/__testfixtures__/refine/output.ts
  codemod/zod-to-valibot/__testfixtures__/transform/input.ts
  codemod/zod-to-valibot/__testfixtures__/transform/output.ts
  codemod/zod-to-valibot/src/test-setup.test.ts
  codemod/zod-to-valibot/src/transform/imports/imports.ts
  codemod/zod-to-valibot/src/transform/index.ts
  codemod/zod-to-valibot/src/transform/schemas-and-links/constants.ts
  codemod/zod-to-valibot/src/transform/schemas-and-links/methods/index.ts
  codemod/zod-to-valibot/src/transform/schemas-and-links/methods/refine/index.ts
  codemod/zod-to-valibot/src/transform/schemas-and-links/methods/refine/refine.ts
  codemod/zod-to-valibot/src/transform/schemas-and-links/methods/transform/index.ts
  codemod/zod-to-valibot/src/transform/schemas-and-links/methods/transform/transform.ts
  codemod/zod-to-valibot/src/transform/schemas-and-links/schemas-and-links.ts
Labels: enhancement, size:L

#1302 docs: add prisma-valibot-generator & drzl to “X → Valibot” ecosystem
  website/src/routes/guides/(get-started)/ecosystem/index.mdx
Labels: documentation, size:XS

#1298 doc: adds `@traversable/valibot` and `@traversable/valibot-test` to ecosystem
  website/src/routes/guides/(get-started)/ecosystem/index.mdx
Labels: documentation, size:XS

#1248 Migrate website to tailwind v4
  pnpm-lock.yaml
  website/package.json
  website/postcss.config.cjs
  website/src/components/ApiList.tsx
  website/src/components/Chapters.tsx
  website/src/components/Credits.tsx
  website/src/components/DocSearch.tsx
  website/src/components/DocsLayout.tsx
  website/src/components/Expandable.tsx
  website/src/components/Footer.tsx
  website/src/components/Header.tsx
  website/src/components/Navigation.tsx
  website/src/components/PostCover.tsx
  website/src/components/PostMeta.tsx
  website/src/components/Property.tsx
  website/src/components/RoutingIndicator.tsx
  website/src/components/SideBar.tsx
  website/src/hooks/useMDXComponents.tsx
  website/src/routes/(legal)/layout.tsx
  website/src/routes/404.tsx
  website/src/routes/blog/(posts)/layout.tsx
  website/src/routes/blog/(posts)/valibot-v0.31.0-is-finally-available/index.mdx
  website/src/routes/blog/(posts)/valibot-v1-the-1-kb-schema-library/index.mdx
  website/src/routes/blog/index.tsx
  website/src/routes/guides/(migration)/migrate-from-zod/CodemodEditor.tsx
  website/src/routes/index.tsx
  website/src/routes/playground/index.tsx
  website/src/styles/pace.css
  website/src/styles/root.css
  website/src/utils/disableTransitions.ts
  website/tailwind.config.cjs
  website/tsconfig.json
  website/vite.config.ts
Labels: documentation, size:L

#1312 chore: fix PR link for Catalan language entry
  packages/i18n/README.md
Labels: documentation, size:XS

#1315 Update contributors and add valibot-serialize entry
  website/src/routes/guides/(get-started)/ecosystem/index.mdx
Labels: documentation, size:XS

#1320 fix: update Guides link in Header component and add source to stringi…
  website/src/components/Header.tsx
  website/src/routes/api/(actions)/stringifyJson/index.mdx
Labels: fix, size:XS
