Repository fabian-hiller/valibot, pull requests merged in 2025-03, with the labels that each got.

#1065 feat: allow custom error message to be empty
  library/CHANGELOG.md
  library/src/utils/_addIssue/_addIssue.test.ts
  library/src/utils/_addIssue/_addIssue.ts
Labels: question

#1068 Strip u flag in email regexp and improve description on v.email
  library/src/regex.ts
Labels: fix

#1064 feat(actions): timestamps with optional "T"
  library/CHANGELOG.md
  library/src/actions/isoDateTime/isoDateTime.test.ts
  library/src/actions/isoDateTime/isoDateTime.ts
  library/src/actions/isoTimestamp/isoTimestamp.test.ts
  library/src/actions/isoTimestamp/isoTimestamp.ts
  library/src/regex.ts
  website/src/routes/api/(actions)/isoDateTime/index.mdx
  website/src/routes/api/(actions)/isoTimestamp/index.mdx
Labels: fix

#1070 Update Romanian translations
  packages/i18n/src/ro.ts
Labels: enhancement

#1086 Change DECIMAL_REGEX to support floats that start with a dot
  library/CHANGELOG.md
  library/src/actions/decimal/decimal.test.ts
  library/src/regex.ts
Labels: enhancement

#1084 Add Valibot v1 blog post to website
  website/src/routes/blog/(posts)/valibot-v0.31.0-is-finally-available/index.mdx
  website/src/routes/blog/(posts)/valibot-v1-rc-is-available/index.mdx
  website/src/routes/blog/(posts)/valibot-v1-the-1-kb-schema-library/index.mdx
  website/src/routes/blog/(posts)/valibot-v1-the-1-kb-schema-library/valibot-talk.webp
  website/src/routes/guides/(get-started)/quick-start/index.mdx
Labels: documentation

#1093 docs: add oRPC to Ecosystem
  website/src/routes/guides/(get-started)/ecosystem/index.mdx
Labels: documentation

#1083 docs: add info on .regex with g flag
  library/src/actions/regex/regex.ts
  website/src/routes/api/(actions)/regex/index.mdx
Labels: documentation

#1110 Improve perf of variant by abort validation of discriminators early
  library/CHANGELOG.md
  library/src/schemas/variant/variant.ts
  library/src/schemas/variant/variantAsync.ts
Labels: enhancement

#1118 Fix stringification of objects with null prototype
  website/src/routes/playground/iframeCode.js
Labels: documentation
